version: "3.9"

services:
  db:
    container_name: poatan
    image: postgres:alpine3.18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: poatan
    volumes:
      - db:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d poatan -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db:
